sudo : required

services:
  - docker

before_install:
  - docker build -t botchway44/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true botchway44/docker-react npm run test -- --coverage


deploy:
  provider : elasticbeanstalk
  region : us-east-1
  app : docker-react
  env : "Dockerreact-env"
  bucket_name : "elasticbeanstalk-us-east-1-874015589004"
  bucket_path : "docker-react"
  on:
    branch : master
  access_key_id : $ACCESS_KEY
  secret_access_key : 
    secure : "$SECRET_KEY"